"""Turn a Markdown-ish report into a downloadable PDF (fpdf2, no system deps)."""
from __future__ import annotations

import re
import uuid

from src.common import resolve, ensure_dir

_REPL = {"•": "-", "—": "-", "–": "-", "’": "'", "‘": "'", "“": '"', "”": '"',
         "≥": ">=", "≤": "<=", "→": "->", "×": "x", "…": "...", "‑": "-"}


def _latin1(s: str) -> str:
    for a, b in _REPL.items():
        s = s.replace(a, b)
    return s.encode("latin-1", "replace").decode("latin-1")


def _wrap_tokens(s: str, n: int = 45) -> str:
    """fpdf2 raises if a single unbroken token is wider than the cell. Hard-split
    any run of non-space characters longer than n so multi_cell can always wrap."""
    out = []
    for tok in s.split(" "):
        while len(tok) > n:
            out.append(tok[:n]); tok = tok[n:]
        out.append(tok)
    return " ".join(out)


def report_to_pdf(text: str, title: str = "MultiMedAI Report"):
    from fpdf import FPDF

    pdf = FPDF()
    pdf.set_auto_page_break(True, 16)
    pdf.add_page()

    def cell(txt, h, style="", size=11):
        # reset x to the left margin first: some fpdf2 versions leave the cursor at
        # the right edge after multi_cell, which makes w=0 and raises "not enough
        # horizontal space". Explicit set_x guarantees full-width wrapping.
        pdf.set_font("Helvetica", style, size)
        pdf.set_x(pdf.l_margin)
        pdf.multi_cell(0, h, _wrap_tokens(txt))

    cell(_latin1(title), 9, "B", 16)
    pdf.ln(2)

    for raw in text.split("\n"):
        line = raw.rstrip()
        if not line.strip():
            pdf.ln(3); continue
        # markdown horizontal rule (---, ***, ___) -> thin separator, not text
        if set(line.strip()) <= {"-", "*", "_", "="} and len(line.strip()) >= 3:
            pdf.ln(1)
            y = pdf.get_y()
            pdf.line(pdf.l_margin, y, pdf.w - pdf.r_margin, y)
            pdf.ln(2); continue
        clean = _latin1(re.sub(r"\*\*(.+?)\*\*", r"\1", line).replace("**", "")
                        .replace("`", "").replace("#", "").strip())
        if line.strip().startswith(("- ", "* ")):
            cell("   - " + clean.lstrip("-* ").strip(), 6, "", 11)
        elif raw.strip().startswith("**") or raw.strip().startswith("#"):
            cell(clean, 7, "B", 12)
        else:
            cell(clean, 6, "", 11)

    pdf.ln(5)
    cell(_latin1("Generated by MultiMedAI - educational/research use only, not a "
                 "diagnosis or treatment advice."), 5, "I", 9)
    out = ensure_dir(resolve("outputs", "web")) / f"report_{uuid.uuid4().hex[:8]}.pdf"
    pdf.output(str(out))
    return out
