"""Turn a Markdown-ish report into a downloadable PDF (fpdf2, no system deps)."""
from __future__ import annotations

import re
import uuid

from src.common import resolve, ensure_dir

_REPL = {"•": "-", "—": "-", "–": "-", "’": "'", "‘": "'", "“": '"', "”": '"',
         "≥": ">=", "≤": "<=", "→": "->", "×": "x", "…": "...", "‑": "-"}


def _latin1(s: str) -> str:
    for a, b in _REPL.items():
        s = s.replace(a, b)
    return s.encode("latin-1", "replace").decode("latin-1")


def report_to_pdf(text: str, title: str = "MultiMedAI Report"):
    from fpdf import FPDF
    pdf = FPDF()
    pdf.set_auto_page_break(True, 16)
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 16)
    pdf.multi_cell(0, 9, _latin1(title))
    pdf.ln(2)

    for raw in text.split("\n"):
        line = raw.rstrip()
        if not line.strip():
            pdf.ln(3); continue
        clean = _latin1(re.sub(r"\*\*(.+?)\*\*", r"\1", line).replace("**", "")
                        .replace("`", "").replace("#", "").strip())
        if line.strip().startswith(("- ", "* ")):
            pdf.set_font("Helvetica", size=11)
            pdf.multi_cell(0, 6, "   - " + clean.lstrip("-* ").strip())
        elif raw.strip().startswith("**") or raw.strip().startswith("#"):
            pdf.set_font("Helvetica", "B", 12)
            pdf.multi_cell(0, 7, clean)
        else:
            pdf.set_font("Helvetica", size=11)
            pdf.multi_cell(0, 6, clean)

    pdf.ln(5)
    pdf.set_font("Helvetica", "I", 9)
    pdf.multi_cell(0, 5, _latin1("Generated by MultiMedAI — educational/research use "
                                 "only, not a diagnosis or treatment advice."))
    out = ensure_dir(resolve("outputs", "web")) / f"report_{uuid.uuid4().hex[:8]}.pdf"
    pdf.output(str(out))
    return out
